2017-07-05 17:10:48,630 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:10:48,694 - DEBUG - Connecting to Server
2017-07-05 17:10:49,708 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:10:50,711 - DEBUG - Requesting historical data
2017-07-05 17:10:50,719 - DEBUG - Returned from Reply Handler
2017-07-05 17:10:51,752 - DEBUG - Disconnecting from Server
2017-07-05 17:10:51,770 - DEBUG - Connecting to Server
2017-07-05 17:10:52,777 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:10:53,780 - DEBUG - Requesting historical data
2017-07-05 17:10:53,783 - DEBUG - Returned from Reply Handler
2017-07-05 17:10:54,787 - DEBUG - Disconnecting from Server
2017-07-05 17:10:54,814 - DEBUG - Connecting to Server
2017-07-05 17:10:55,821 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:10:56,828 - DEBUG - Requesting historical data
2017-07-05 17:10:56,844 - DEBUG - Returned from Reply Handler
2017-07-05 17:10:56,931 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:10:56,948 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:10:57,856 - DEBUG - Disconnecting from Server
2017-07-05 17:10:57,909 - DEBUG - Connecting to Server
2017-07-05 17:10:58,916 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:10:59,921 - DEBUG - Requesting historical data
2017-07-05 17:10:59,939 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:00,371 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:00,375 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:00,946 - DEBUG - Disconnecting from Server
2017-07-05 17:11:00,988 - DEBUG - Connecting to Server
2017-07-05 17:11:01,990 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:11:02,994 - DEBUG - Requesting historical data
2017-07-05 17:11:03,020 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:03,980 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:03,985 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:04,034 - DEBUG - Disconnecting from Server
2017-07-05 17:11:04,044 - DEBUG - Connecting to Server
2017-07-05 17:11:05,051 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:11:06,055 - DEBUG - Requesting historical data
2017-07-05 17:11:06,067 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:06,163 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:06,175 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:07,074 - DEBUG - Disconnecting from Server
2017-07-05 17:11:07,100 - DEBUG - Connecting to Server
2017-07-05 17:11:08,104 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:11:09,107 - DEBUG - Requesting historical data
2017-07-05 17:11:09,119 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:09,215 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:09,221 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:10,126 - DEBUG - Disconnecting from Server
2017-07-05 17:11:10,167 - DEBUG - Connecting to Server
2017-07-05 17:11:11,170 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:11:12,173 - DEBUG - Requesting historical data
2017-07-05 17:11:12,181 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:12,290 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:12,294 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:13,187 - DEBUG - Disconnecting from Server
2017-07-05 17:11:13,220 - DEBUG - Connecting to Server
2017-07-05 17:11:14,223 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:11:15,230 - DEBUG - Requesting historical data
2017-07-05 17:11:15,240 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:15,425 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:15,433 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:16,246 - DEBUG - Disconnecting from Server
2017-07-05 17:11:16,282 - DEBUG - Connecting to Server
2017-07-05 17:11:17,285 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:11:18,288 - DEBUG - Requesting historical data
2017-07-05 17:11:18,301 - DEBUG - Returned from Reply Handler
2017-07-05 17:11:18,523 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:18,531 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 45, in reply_handler
    test5 - msg.volume
NameError: name 'test5' is not defined
2017-07-05 17:11:19,322 - DEBUG - Disconnecting from Server
2017-07-05 17:11:19,366 - DEBUG - Connecting to Server
2017-07-05 17:12:43,945 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:12:43,962 - DEBUG - Connecting to Server
2017-07-05 17:12:44,970 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:12:45,981 - DEBUG - Requesting historical data
2017-07-05 17:12:45,991 - DEBUG - Returned from Reply Handler
2017-07-05 17:12:47,001 - DEBUG - Disconnecting from Server
2017-07-05 17:12:47,034 - DEBUG - Connecting to Server
2017-07-05 17:12:48,041 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:12:49,049 - DEBUG - Requesting historical data
2017-07-05 17:12:49,056 - DEBUG - Returned from Reply Handler
2017-07-05 17:12:50,068 - DEBUG - Disconnecting from Server
2017-07-05 17:12:50,103 - DEBUG - Connecting to Server
2017-07-05 17:12:51,111 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:12:52,118 - DEBUG - Requesting historical data
2017-07-05 17:12:52,125 - DEBUG - Returned from Reply Handler
2017-07-05 17:12:53,132 - DEBUG - Disconnecting from Server
2017-07-05 17:12:53,167 - DEBUG - Connecting to Server
2017-07-05 17:12:54,173 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:12:55,180 - DEBUG - Requesting historical data
2017-07-05 17:12:55,187 - DEBUG - Returned from Reply Handler
2017-07-05 17:12:56,197 - DEBUG - Disconnecting from Server
2017-07-05 17:12:56,256 - DEBUG - Connecting to Server
2017-07-05 17:12:57,290 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:12:58,297 - DEBUG - Requesting historical data
2017-07-05 17:12:58,304 - DEBUG - Returned from Reply Handler
2017-07-05 17:12:59,317 - DEBUG - Disconnecting from Server
2017-07-05 17:12:59,341 - DEBUG - Connecting to Server
2017-07-05 17:13:00,349 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:01,356 - DEBUG - Requesting historical data
2017-07-05 17:13:01,363 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:02,371 - DEBUG - Disconnecting from Server
2017-07-05 17:13:02,402 - DEBUG - Connecting to Server
2017-07-05 17:13:03,414 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:04,421 - DEBUG - Requesting historical data
2017-07-05 17:13:04,430 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:05,440 - DEBUG - Disconnecting from Server
2017-07-05 17:13:05,466 - DEBUG - Connecting to Server
2017-07-05 17:13:06,480 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:44,224 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:13:44,255 - DEBUG - Connecting to Server
2017-07-05 17:13:45,265 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:46,283 - DEBUG - Requesting historical data
2017-07-05 17:13:46,297 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:47,310 - DEBUG - Disconnecting from Server
2017-07-05 17:13:47,350 - DEBUG - Connecting to Server
2017-07-05 17:13:48,362 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:49,377 - DEBUG - Requesting historical data
2017-07-05 17:13:49,392 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:50,406 - DEBUG - Disconnecting from Server
2017-07-05 17:13:50,448 - DEBUG - Connecting to Server
2017-07-05 17:13:51,461 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:52,478 - DEBUG - Requesting historical data
2017-07-05 17:13:52,496 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:53,508 - DEBUG - Disconnecting from Server
2017-07-05 17:13:53,544 - DEBUG - Connecting to Server
2017-07-05 17:13:54,554 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:55,570 - DEBUG - Requesting historical data
2017-07-05 17:13:55,586 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:56,605 - DEBUG - Disconnecting from Server
2017-07-05 17:13:56,635 - DEBUG - Connecting to Server
2017-07-05 17:13:57,652 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:13:58,667 - DEBUG - Requesting historical data
2017-07-05 17:13:58,683 - DEBUG - Returned from Reply Handler
2017-07-05 17:13:59,699 - DEBUG - Disconnecting from Server
2017-07-05 17:13:59,731 - DEBUG - Connecting to Server
2017-07-05 17:14:00,740 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:14:01,754 - DEBUG - Requesting historical data
2017-07-05 17:14:01,769 - DEBUG - Returned from Reply Handler
2017-07-05 17:14:02,780 - DEBUG - Disconnecting from Server
2017-07-05 17:14:02,813 - DEBUG - Connecting to Server
2017-07-05 17:14:03,821 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:14:04,835 - DEBUG - Requesting historical data
2017-07-05 17:14:04,847 - DEBUG - Returned from Reply Handler
2017-07-05 17:14:05,859 - DEBUG - Disconnecting from Server
2017-07-05 17:14:05,894 - DEBUG - Connecting to Server
2017-07-05 17:14:06,906 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:14:07,924 - DEBUG - Requesting historical data
2017-07-05 17:14:07,936 - DEBUG - Returned from Reply Handler
2017-07-05 17:14:18,399 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:14:18,427 - DEBUG - Connecting to Server
2017-07-05 17:14:19,441 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:14:20,458 - DEBUG - Requesting historical data
2017-07-05 17:14:20,484 - DEBUG - Returned from Reply Handler
2017-07-05 17:14:20,611 - DEBUG - In Reply Handler
2017-07-05 17:14:20,626 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:14:21,414 - DEBUG - Connected to Database
2017-07-05 17:14:21,461 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close, Volume) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:14:21,486 - DEBUG - In Reply Handler
2017-07-05 17:14:21,505 - DEBUG - Disconnecting from Server
2017-07-05 17:14:21,523 - DEBUG - Connecting to Server
2017-07-05 17:14:22,538 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:14:23,555 - DEBUG - Requesting historical data
2017-07-05 17:14:23,585 - DEBUG - Returned from Reply Handler
2017-07-05 17:14:24,114 - DEBUG - In Reply Handler
2017-07-05 17:14:24,122 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:14:24,251 - DEBUG - Connected to Database
2017-07-05 17:14:24,291 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close, Volume) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:14:24,309 - DEBUG - In Reply Handler
2017-07-05 17:14:24,606 - DEBUG - Disconnecting from Server
2017-07-05 17:14:24,646 - DEBUG - Connecting to Server
2017-07-05 17:14:25,665 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:14:26,688 - DEBUG - Requesting historical data
2017-07-05 17:14:26,722 - DEBUG - Returned from Reply Handler
2017-07-05 17:14:26,796 - DEBUG - In Reply Handler
2017-07-05 17:14:26,808 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:14:26,995 - DEBUG - Connected to Database
2017-07-05 17:14:27,036 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close, Volume) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:14:27,059 - DEBUG - In Reply Handler
2017-07-05 17:14:27,737 - DEBUG - Disconnecting from Server
2017-07-05 17:14:27,777 - DEBUG - Connecting to Server
2017-07-05 17:14:28,816 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:15:27,887 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:15:27,919 - DEBUG - Connecting to Server
2017-07-05 17:15:28,934 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:15:29,958 - DEBUG - Requesting historical data
2017-07-05 17:15:29,989 - DEBUG - Returned from Reply Handler
2017-07-05 17:15:30,071 - DEBUG - In Reply Handler
2017-07-05 17:15:30,085 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:15:30,485 - DEBUG - Connected to Database
2017-07-05 17:15:30,530 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:15:30,548 - DEBUG - In Reply Handler
2017-07-05 17:15:31,007 - DEBUG - Disconnecting from Server
2017-07-05 17:15:31,049 - DEBUG - Connecting to Server
2017-07-05 17:15:32,065 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:15:33,092 - DEBUG - Requesting historical data
2017-07-05 17:15:33,123 - DEBUG - Returned from Reply Handler
2017-07-05 17:15:33,207 - DEBUG - In Reply Handler
2017-07-05 17:15:33,217 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:15:34,143 - DEBUG - Disconnecting from Server
2017-07-05 17:15:34,188 - DEBUG - Connected to Database
2017-07-05 17:15:34,189 - DEBUG - Connecting to Server
2017-07-05 17:15:34,229 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:15:34,240 - DEBUG - In Reply Handler
2017-07-05 17:15:35,207 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:15:36,225 - DEBUG - Requesting historical data
2017-07-05 17:15:36,251 - DEBUG - Returned from Reply Handler
2017-07-05 17:15:36,347 - DEBUG - In Reply Handler
2017-07-05 17:15:36,367 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:15:36,819 - DEBUG - Connected to Database
2017-07-05 17:15:36,867 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:15:36,883 - DEBUG - In Reply Handler
2017-07-05 17:15:37,267 - DEBUG - Disconnecting from Server
2017-07-05 17:15:37,309 - DEBUG - Connecting to Server
2017-07-05 17:15:38,322 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:15:39,344 - DEBUG - Requesting historical data
2017-07-05 17:15:39,373 - DEBUG - Returned from Reply Handler
2017-07-05 17:15:39,446 - DEBUG - In Reply Handler
2017-07-05 17:15:39,457 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:15:39,604 - DEBUG - Connected to Database
2017-07-05 17:15:39,645 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:15:39,665 - DEBUG - In Reply Handler
2017-07-05 17:18:15,709 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:18:15,732 - DEBUG - Connecting to Server
2017-07-05 17:18:16,751 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:17,779 - DEBUG - Requesting historical data
2017-07-05 17:18:17,808 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:18,822 - DEBUG - Disconnecting from Server
2017-07-05 17:18:18,861 - DEBUG - Connecting to Server
2017-07-05 17:18:19,881 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:20,903 - DEBUG - Requesting historical data
2017-07-05 17:18:20,930 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:21,948 - DEBUG - Disconnecting from Server
2017-07-05 17:18:21,994 - DEBUG - Connecting to Server
2017-07-05 17:18:23,016 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:24,037 - DEBUG - Requesting historical data
2017-07-05 17:18:24,062 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:25,082 - DEBUG - Disconnecting from Server
2017-07-05 17:18:25,135 - DEBUG - Connecting to Server
2017-07-05 17:18:26,164 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:27,199 - DEBUG - Requesting historical data
2017-07-05 17:18:27,227 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:49,866 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:18:49,889 - DEBUG - Connecting to Server
2017-07-05 17:18:50,893 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:51,896 - DEBUG - Requesting historical data
2017-07-05 17:18:51,901 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:51,987 - DEBUG - In Reply Handler
2017-07-05 17:18:52,001 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:18:52,167 - DEBUG - Connected to Database
2017-07-05 17:18:52,192 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:18:52,198 - DEBUG - In Reply Handler
2017-07-05 17:18:52,919 - DEBUG - Disconnecting from Server
2017-07-05 17:18:52,999 - DEBUG - Connecting to Server
2017-07-05 17:18:54,003 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:55,007 - DEBUG - Requesting historical data
2017-07-05 17:18:55,021 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:55,147 - DEBUG - In Reply Handler
2017-07-05 17:18:55,151 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:18:55,270 - DEBUG - Connected to Database
2017-07-05 17:18:55,297 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:18:55,303 - DEBUG - In Reply Handler
2017-07-05 17:18:56,028 - DEBUG - Disconnecting from Server
2017-07-05 17:18:56,063 - DEBUG - Connecting to Server
2017-07-05 17:18:57,066 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:18:58,069 - DEBUG - Requesting historical data
2017-07-05 17:18:58,088 - DEBUG - Returned from Reply Handler
2017-07-05 17:18:58,181 - DEBUG - In Reply Handler
2017-07-05 17:18:58,185 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:18:58,586 - DEBUG - Connected to Database
2017-07-05 17:18:58,619 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:18:58,624 - DEBUG - In Reply Handler
2017-07-05 17:18:59,094 - DEBUG - Disconnecting from Server
2017-07-05 17:18:59,135 - DEBUG - Connecting to Server
2017-07-05 17:19:00,137 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:19:01,140 - DEBUG - Requesting historical data
2017-07-05 17:19:01,158 - DEBUG - Returned from Reply Handler
2017-07-05 17:19:01,446 - DEBUG - In Reply Handler
2017-07-05 17:19:01,450 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:19:01,588 - DEBUG - Connected to Database
2017-07-05 17:19:01,612 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:19:01,618 - DEBUG - In Reply Handler
2017-07-05 17:19:02,162 - DEBUG - Disconnecting from Server
2017-07-05 17:19:02,223 - DEBUG - Connecting to Server
2017-07-05 17:19:03,227 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:19:04,230 - DEBUG - Requesting historical data
2017-07-05 17:19:04,251 - DEBUG - Returned from Reply Handler
2017-07-05 17:19:04,344 - DEBUG - In Reply Handler
2017-07-05 17:19:04,353 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:19:04,531 - DEBUG - Connected to Database
2017-07-05 17:19:04,557 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:19:04,566 - DEBUG - In Reply Handler
2017-07-05 17:19:05,260 - DEBUG - Disconnecting from Server
2017-07-05 17:19:05,306 - DEBUG - Connecting to Server
2017-07-05 17:19:06,316 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:21:09,535 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:21:09,567 - DEBUG - Connecting to Server
2017-07-05 17:21:10,573 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:21:11,580 - DEBUG - Requesting historical data
2017-07-05 17:21:11,588 - DEBUG - Returned from Reply Handler
2017-07-05 17:21:12,598 - DEBUG - Disconnecting from Server
2017-07-05 17:21:12,622 - DEBUG - Connecting to Server
2017-07-05 17:21:13,626 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:21:14,634 - DEBUG - Requesting historical data
2017-07-05 17:21:14,641 - DEBUG - Returned from Reply Handler
2017-07-05 17:21:15,652 - DEBUG - Disconnecting from Server
2017-07-05 17:21:15,683 - DEBUG - Connecting to Server
2017-07-05 17:21:16,688 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:21:17,695 - DEBUG - Requesting historical data
2017-07-05 17:21:17,702 - DEBUG - Returned from Reply Handler
2017-07-05 17:21:18,713 - DEBUG - Disconnecting from Server
2017-07-05 17:21:18,757 - DEBUG - Connecting to Server
2017-07-05 17:21:19,763 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:21:20,770 - DEBUG - Requesting historical data
2017-07-05 17:21:20,777 - DEBUG - Returned from Reply Handler
2017-07-05 17:21:21,789 - DEBUG - Disconnecting from Server
2017-07-05 17:22:25,807 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:22:25,834 - DEBUG - Connecting to Server
2017-07-05 17:22:26,837 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:22:27,838 - DEBUG - Requesting historical data
2017-07-05 17:22:27,854 - DEBUG - Returned from Reply Handler
2017-07-05 17:22:28,586 - DEBUG - In Reply Handler
2017-07-05 17:22:28,587 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:22:28,875 - DEBUG - Disconnecting from Server
2017-07-05 17:22:28,914 - DEBUG - Connecting to Server
2017-07-05 17:22:29,002 - DEBUG - Connected to Database
2017-07-05 17:22:29,032 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + "(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:22:29,037 - DEBUG - In Reply Handler
2017-07-05 17:22:29,918 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:22:30,919 - DEBUG - Requesting historical data
2017-07-05 17:22:30,941 - DEBUG - Returned from Reply Handler
2017-07-05 17:22:31,012 - DEBUG - In Reply Handler
2017-07-05 17:22:31,015 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:22:31,141 - DEBUG - Connected to Database
2017-07-05 17:22:31,167 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + "(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:22:31,172 - DEBUG - In Reply Handler
2017-07-05 17:22:31,952 - DEBUG - Disconnecting from Server
2017-07-05 17:22:32,022 - DEBUG - Connecting to Server
2017-07-05 17:22:33,025 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:22:34,026 - DEBUG - Requesting historical data
2017-07-05 17:22:34,032 - DEBUG - Returned from Reply Handler
2017-07-05 17:22:34,123 - DEBUG - In Reply Handler
2017-07-05 17:22:34,127 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:22:34,524 - DEBUG - Connected to Database
2017-07-05 17:22:34,565 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + "(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:22:34,570 - DEBUG - In Reply Handler
2017-07-05 17:22:35,052 - DEBUG - Disconnecting from Server
2017-07-05 17:22:35,090 - DEBUG - Connecting to Server
2017-07-05 17:22:36,096 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:22:37,099 - DEBUG - Requesting historical data
2017-07-05 17:22:37,108 - DEBUG - Returned from Reply Handler
2017-07-05 17:22:37,214 - DEBUG - In Reply Handler
2017-07-05 17:22:37,216 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:22:37,342 - DEBUG - Connected to Database
2017-07-05 17:22:37,370 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + "(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:22:37,375 - DEBUG - In Reply Handler
2017-07-05 17:22:38,110 - DEBUG - Disconnecting from Server
2017-07-05 17:22:38,142 - DEBUG - Connecting to Server
2017-07-05 17:22:39,150 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:23:57,670 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:23:57,689 - DEBUG - Connecting to Server
2017-07-05 17:23:58,692 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:23:59,695 - DEBUG - Requesting historical data
2017-07-05 17:23:59,706 - DEBUG - Returned from Reply Handler
2017-07-05 17:23:59,821 - DEBUG - In Reply Handler
2017-07-05 17:23:59,824 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:24:00,259 - DEBUG - Connected to Database
2017-07-05 17:24:00,287 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("""Insert Into E7 (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:24:00,295 - DEBUG - In Reply Handler
2017-07-05 17:24:00,726 - DEBUG - Disconnecting from Server
2017-07-05 17:24:00,792 - DEBUG - Connecting to Server
2017-07-05 17:24:01,800 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:24:02,804 - DEBUG - Requesting historical data
2017-07-05 17:24:02,824 - DEBUG - Returned from Reply Handler
2017-07-05 17:24:02,908 - DEBUG - In Reply Handler
2017-07-05 17:24:02,911 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:24:03,035 - DEBUG - Connected to Database
2017-07-05 17:24:03,060 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("""Insert Into E7 (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:24:03,066 - DEBUG - In Reply Handler
2017-07-05 17:24:03,835 - DEBUG - Disconnecting from Server
2017-07-05 17:24:03,867 - DEBUG - Connecting to Server
2017-07-05 17:24:04,868 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:24:05,871 - DEBUG - Requesting historical data
2017-07-05 17:24:05,885 - DEBUG - Returned from Reply Handler
2017-07-05 17:24:05,998 - DEBUG - In Reply Handler
2017-07-05 17:24:06,002 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:24:06,225 - DEBUG - Connected to Database
2017-07-05 17:24:06,268 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("""Insert Into E7 (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:24:06,274 - DEBUG - In Reply Handler
2017-07-05 17:24:06,894 - DEBUG - Disconnecting from Server
2017-07-05 17:24:06,938 - DEBUG - Connecting to Server
2017-07-05 17:24:07,942 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:24:08,945 - DEBUG - Requesting historical data
2017-07-05 17:24:08,965 - DEBUG - Returned from Reply Handler
2017-07-05 17:24:09,045 - DEBUG - In Reply Handler
2017-07-05 17:24:09,047 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:24:09,184 - DEBUG - Connected to Database
2017-07-05 17:24:09,219 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("""Insert Into E7 (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:24:09,224 - DEBUG - In Reply Handler
2017-07-05 17:24:09,977 - DEBUG - Disconnecting from Server
2017-07-05 17:24:10,010 - DEBUG - Connecting to Server
2017-07-05 17:26:09,581 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:26:09,619 - DEBUG - Connecting to Server
2017-07-05 17:26:10,625 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:26:11,633 - DEBUG - Requesting historical data
2017-07-05 17:26:11,640 - DEBUG - Returned from Reply Handler
2017-07-05 17:26:12,652 - DEBUG - Disconnecting from Server
2017-07-05 17:26:12,687 - DEBUG - Connecting to Server
2017-07-05 17:26:13,693 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:26:14,700 - DEBUG - Requesting historical data
2017-07-05 17:26:14,708 - DEBUG - Returned from Reply Handler
2017-07-05 17:27:10,877 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:27:10,898 - DEBUG - Connecting to Server
2017-07-05 17:27:11,902 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:27:12,906 - DEBUG - Requesting historical data
2017-07-05 17:27:12,912 - DEBUG - Returned from Reply Handler
2017-07-05 17:27:13,008 - DEBUG - In Reply Handler
2017-07-05 17:27:13,011 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:27:13,168 - DEBUG - Connected to Database
2017-07-05 17:27:13,260 - DEBUG - Ran Insert Script
2017-07-05 17:27:13,262 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:27:13,264 - DEBUG - Today is still  2017-07-05
2017-07-05 17:27:13,267 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:27:13,269 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:27:13,271 - DEBUG - Query is SELECT ID from E7 where Date = "07/04/2017"
2017-07-05 17:27:13,299 - DEBUG - BB ID1 is (72,)
2017-07-05 17:27:13,302 - DEBUG - BB ID1 is (73,)
2017-07-05 17:27:13,305 - DEBUG - BB ID1 is (74,)
2017-07-05 17:27:13,308 - DEBUG - BB ID1 is (75,)
2017-07-05 17:27:13,312 - DEBUG - BB ID1 is (76,)
2017-07-05 17:27:13,314 - DEBUG - Query is SELECT ID from E7 where Date = "06/22/2017"
2017-07-05 17:27:13,339 - DEBUG - BB ID1 is (76,)
2017-07-05 17:27:13,341 - DEBUG - BB ID2 is (51,)
2017-07-05 17:27:13,342 - DEBUG - Query is SELECT round(Avg(Close),5) as Avg from E7 where ID BETWEEN 51 AND 76;
2017-07-05 17:27:13,367 - DEBUG - BBMovAvg is (1.13831,)
2017-07-05 17:27:13,369 - DEBUG - Query is UPDATE hasPosition SET BB_STRATMovingAvgValue = 1.13831 where CCY ='E7';
2017-07-05 17:27:13,430 - DEBUG - Flag set to 1
2017-07-05 17:27:13,433 - DEBUG - In Reply Handler
2017-07-05 17:27:13,915 - DEBUG - Disconnecting from Server
2017-07-05 17:27:13,922 - DEBUG - Finished E7 Daily OHLC
2017-07-05 17:28:57,360 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:28:57,376 - DEBUG - Connecting to Server
2017-07-05 17:28:58,379 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:28:59,382 - DEBUG - Requesting historical data
2017-07-05 17:28:59,395 - DEBUG - Returned from Reply Handler
2017-07-05 17:28:59,486 - DEBUG - In Reply Handler
2017-07-05 17:28:59,492 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:28:59,934 - DEBUG - Connected to Database
2017-07-05 17:28:59,986 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into"+ Table + """(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'SERPDB01.IntoE7' doesn't exist
2017-07-05 17:29:00,049 - DEBUG - In Reply Handler
2017-07-05 17:29:00,402 - DEBUG - Disconnecting from Server
2017-07-05 17:29:00,441 - DEBUG - Connecting to Server
2017-07-05 17:29:01,445 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:29:02,448 - DEBUG - Requesting historical data
2017-07-05 17:29:02,461 - DEBUG - Returned from Reply Handler
2017-07-05 17:29:02,581 - DEBUG - In Reply Handler
2017-07-05 17:29:02,590 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:29:02,728 - DEBUG - Connected to Database
2017-07-05 17:29:02,780 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into"+ Table + """(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'SERPDB01.IntoE7' doesn't exist
2017-07-05 17:29:02,789 - DEBUG - In Reply Handler
2017-07-05 17:29:03,484 - DEBUG - Disconnecting from Server
2017-07-05 17:29:03,528 - DEBUG - Connecting to Server
2017-07-05 17:29:04,531 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:29:05,534 - DEBUG - Requesting historical data
2017-07-05 17:29:05,546 - DEBUG - Returned from Reply Handler
2017-07-05 17:29:05,619 - DEBUG - In Reply Handler
2017-07-05 17:29:05,623 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:29:05,791 - DEBUG - Connected to Database
2017-07-05 17:29:05,845 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into"+ Table + """(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'SERPDB01.IntoE7' doesn't exist
2017-07-05 17:29:05,851 - DEBUG - In Reply Handler
2017-07-05 17:29:06,553 - DEBUG - Disconnecting from Server
2017-07-05 17:29:06,588 - DEBUG - Connecting to Server
2017-07-05 17:29:07,594 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:29:08,597 - DEBUG - Requesting historical data
2017-07-05 17:29:08,615 - DEBUG - Returned from Reply Handler
2017-07-05 17:29:08,680 - DEBUG - In Reply Handler
2017-07-05 17:29:08,682 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:29:08,830 - DEBUG - Connected to Database
2017-07-05 17:29:08,876 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/E7dailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into"+ Table + """(Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'SERPDB01.IntoE7' doesn't exist
2017-07-05 17:29:08,879 - DEBUG - In Reply Handler
2017-07-05 17:29:40,350 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:29:40,366 - DEBUG - Connecting to Server
2017-07-05 17:29:41,368 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:29:42,369 - DEBUG - Requesting historical data
2017-07-05 17:29:42,377 - DEBUG - Returned from Reply Handler
2017-07-05 17:29:42,458 - DEBUG - In Reply Handler
2017-07-05 17:29:42,464 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:29:42,874 - DEBUG - Connected to Database
2017-07-05 17:29:42,973 - DEBUG - Ran Insert Script
2017-07-05 17:29:42,976 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:29:42,980 - DEBUG - Today is still  2017-07-05
2017-07-05 17:29:42,983 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:29:42,987 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:29:42,990 - DEBUG - Query is SELECT ID from E7 where Date = "07/04/2017"
2017-07-05 17:29:43,016 - DEBUG - BB ID1 is (72,)
2017-07-05 17:29:43,019 - DEBUG - BB ID1 is (73,)
2017-07-05 17:29:43,022 - DEBUG - BB ID1 is (74,)
2017-07-05 17:29:43,025 - DEBUG - BB ID1 is (75,)
2017-07-05 17:29:43,028 - DEBUG - BB ID1 is (76,)
2017-07-05 17:29:43,031 - DEBUG - Query is SELECT ID from E7 where Date = "06/22/2017"
2017-07-05 17:29:43,057 - DEBUG - BB ID1 is (76,)
2017-07-05 17:29:43,058 - DEBUG - BB ID2 is (51,)
2017-07-05 17:29:43,062 - DEBUG - Query is SELECT round(Avg(Close),5) as Avg from E7 where ID BETWEEN 51 AND 76;
2017-07-05 17:29:43,097 - DEBUG - BBMovAvg is (1.13831,)
2017-07-05 17:29:43,099 - DEBUG - Query is UPDATE hasPosition SET BB_STRATMovingAvgValue = 1.13831 where CCY ='E7';
2017-07-05 17:29:43,156 - DEBUG - Flag set to 1
2017-07-05 17:29:43,159 - DEBUG - In Reply Handler
2017-07-05 17:29:43,383 - DEBUG - Disconnecting from Server
2017-07-05 17:29:43,386 - DEBUG - Finished E7 Daily OHLC
2017-07-05 17:30:12,214 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:30:12,226 - DEBUG - Connecting to Server
2017-07-05 17:30:13,231 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:30:14,240 - DEBUG - Requesting historical data
2017-07-05 17:30:14,255 - DEBUG - Returned from Reply Handler
2017-07-05 17:30:14,336 - DEBUG - In Reply Handler
2017-07-05 17:30:14,344 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:30:14,785 - DEBUG - Connected to Database
2017-07-05 17:30:14,883 - DEBUG - Ran Insert Script
2017-07-05 17:30:14,890 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:30:14,899 - DEBUG - Today is still  2017-07-05
2017-07-05 17:30:14,908 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:30:14,916 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:30:14,925 - DEBUG - Query is SELECT ID from E7 where Date = "07/04/2017"
2017-07-05 17:30:14,953 - DEBUG - BB ID1 is (72,)
2017-07-05 17:30:14,957 - DEBUG - BB ID1 is (73,)
2017-07-05 17:30:14,962 - DEBUG - BB ID1 is (74,)
2017-07-05 17:30:14,967 - DEBUG - BB ID1 is (75,)
2017-07-05 17:30:14,971 - DEBUG - BB ID1 is (76,)
2017-07-05 17:30:14,975 - DEBUG - Query is SELECT ID from E7 where Date = "06/22/2017"
2017-07-05 17:30:15,001 - DEBUG - BB ID1 is (76,)
2017-07-05 17:30:15,004 - DEBUG - BB ID2 is (51,)
2017-07-05 17:30:15,008 - DEBUG - Query is SELECT round(Avg(Close),5) as Avg from E7 where ID BETWEEN 51 AND 76;
2017-07-05 17:30:15,035 - DEBUG - BBMovAvg is (1.13831,)
2017-07-05 17:30:15,038 - DEBUG - Query is UPDATE hasPosition SET BB_STRATMovingAvgValue = 1.13831 where CCY ='E7';
2017-07-05 17:30:15,107 - DEBUG - Flag set to 1
2017-07-05 17:30:15,116 - DEBUG - In Reply Handler
2017-07-05 17:30:15,269 - DEBUG - Disconnecting from Server
2017-07-05 17:30:15,280 - DEBUG - Finished E7 Daily OHLC
2017-07-05 17:31:13,988 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:31:14,016 - DEBUG - Connecting to Server
2017-07-05 17:31:15,030 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:31:16,045 - DEBUG - Requesting historical data
2017-07-05 17:31:16,067 - DEBUG - Returned from Reply Handler
2017-07-05 17:31:16,143 - DEBUG - test5 -1
2017-07-05 17:31:16,154 - DEBUG - In Reply Handler
2017-07-05 17:31:16,161 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:31:16,546 - DEBUG - Connected to Database
2017-07-05 17:31:16,653 - DEBUG - Ran Insert Script
2017-07-05 17:31:16,667 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:31:16,679 - DEBUG - Today is still  2017-07-05
2017-07-05 17:31:16,692 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:31:16,702 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:31:16,708 - DEBUG - Query is SELECT ID from E7 where Date = "07/04/2017"
2017-07-05 17:31:16,734 - DEBUG - BB ID1 is (72,)
2017-07-05 17:31:16,740 - DEBUG - BB ID1 is (73,)
2017-07-05 17:31:16,747 - DEBUG - BB ID1 is (74,)
2017-07-05 17:31:16,754 - DEBUG - BB ID1 is (75,)
2017-07-05 17:31:16,761 - DEBUG - BB ID1 is (76,)
2017-07-05 17:31:16,767 - DEBUG - Query is SELECT ID from E7 where Date = "06/22/2017"
2017-07-05 17:31:16,797 - DEBUG - BB ID1 is (76,)
2017-07-05 17:31:16,802 - DEBUG - BB ID2 is (51,)
2017-07-05 17:31:16,808 - DEBUG - Query is SELECT round(Avg(Close),5) as Avg from E7 where ID BETWEEN 51 AND 76;
2017-07-05 17:31:16,844 - DEBUG - BBMovAvg is (1.13831,)
2017-07-05 17:31:16,850 - DEBUG - Query is UPDATE hasPosition SET BB_STRATMovingAvgValue = 1.13831 where CCY ='E7';
2017-07-05 17:31:16,915 - DEBUG - Flag set to 1
2017-07-05 17:31:16,927 - DEBUG - test5 -1
2017-07-05 17:31:16,939 - DEBUG - In Reply Handler
2017-07-05 17:31:17,089 - DEBUG - Disconnecting from Server
2017-07-05 17:31:17,102 - DEBUG - Finished E7 Daily OHLC
2017-07-05 17:31:49,690 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:31:49,728 - DEBUG - Connecting to Server
2017-07-05 17:31:50,737 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:31:51,759 - DEBUG - Requesting historical data
2017-07-05 17:31:51,798 - DEBUG - Returned from Reply Handler
2017-07-05 17:31:52,282 - DEBUG - In Reply Handler
2017-07-05 17:31:52,295 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:31:52,469 - DEBUG - Connected to Database
2017-07-05 17:31:52,510 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:31:52,530 - DEBUG - In Reply Handler
2017-07-05 17:31:52,809 - DEBUG - Disconnecting from Server
2017-07-05 17:31:52,844 - DEBUG - Connecting to Server
2017-07-05 17:31:53,857 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:31:54,876 - DEBUG - Requesting historical data
2017-07-05 17:31:54,902 - DEBUG - Returned from Reply Handler
2017-07-05 17:31:54,994 - DEBUG - In Reply Handler
2017-07-05 17:31:55,008 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:31:55,158 - DEBUG - Connected to Database
2017-07-05 17:31:55,222 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 65, in __call__
    return bytes(self.params[index])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/ESdailyOHLC.py", line 56, in reply_handler
    cur.execute("Insert Into " + Table + """  (Date, Open, High, Low, Close) values(%s,%s,%s,%s,%s,%s)""",(time.strftime("%m/%d/%Y"),float(test),float(test2),float(test3),float(test4)))
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 495, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\mysql\connector\cursor.py", line 68, in __call__
    "Not enough parameters for the SQL statement")
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2017-07-05 17:31:55,235 - DEBUG - In Reply Handler
2017-07-05 17:31:55,923 - DEBUG - Disconnecting from Server
2017-07-05 17:31:55,972 - DEBUG - Connecting to Server
2017-07-05 17:33:23,288 - DEBUG - Starting E7DailyOHLC
2017-07-05 17:33:23,341 - DEBUG - Connecting to Server
2017-07-05 17:33:24,360 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:33:25,383 - DEBUG - Requesting historical data
2017-07-05 17:33:25,411 - DEBUG - Returned from Reply Handler
2017-07-05 17:33:25,489 - DEBUG - test5 -1
2017-07-05 17:33:25,507 - DEBUG - In Reply Handler
2017-07-05 17:33:25,518 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:33:25,688 - DEBUG - Connected to Database
2017-07-05 17:33:25,826 - DEBUG - Ran Insert Script
2017-07-05 17:33:25,848 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:33:25,862 - DEBUG - Today is still  2017-07-05
2017-07-05 17:33:25,876 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:33:25,887 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:33:25,900 - DEBUG - Query is SELECT ID from E7 where Date = "07/04/2017"
2017-07-05 17:33:25,931 - DEBUG - BB ID1 is (72,)
2017-07-05 17:33:25,943 - DEBUG - BB ID1 is (73,)
2017-07-05 17:33:25,954 - DEBUG - BB ID1 is (74,)
2017-07-05 17:33:25,965 - DEBUG - BB ID1 is (75,)
2017-07-05 17:33:25,976 - DEBUG - BB ID1 is (76,)
2017-07-05 17:33:25,985 - DEBUG - Query is SELECT ID from E7 where Date = "06/22/2017"
2017-07-05 17:33:26,017 - DEBUG - BB ID1 is (76,)
2017-07-05 17:33:26,026 - DEBUG - BB ID2 is (51,)
2017-07-05 17:33:26,037 - DEBUG - Query is SELECT round(Avg(Close),5) as Avg from E7 where ID BETWEEN 51 AND 76;
2017-07-05 17:33:26,068 - DEBUG - BBMovAvg is (1.13831,)
2017-07-05 17:33:26,083 - DEBUG - Query is UPDATE hasPosition SET BB_STRATMovingAvgValue = 1.13831 where CCY ='E7';
2017-07-05 17:33:26,158 - DEBUG - Flag set to 1
2017-07-05 17:33:26,171 - DEBUG - test5 -1
2017-07-05 17:33:26,180 - DEBUG - In Reply Handler
2017-07-05 17:33:26,437 - DEBUG - Disconnecting from Server
2017-07-05 17:33:26,478 - DEBUG - Finished E7 Daily OHLC
2017-07-05 17:37:45,711 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:37:45,740 - DEBUG - Connecting to Server
2017-07-05 17:37:46,758 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:37:47,778 - DEBUG - Requesting historical data
2017-07-05 17:37:47,815 - DEBUG - Returned from Reply Handler
2017-07-05 17:37:48,830 - DEBUG - Disconnecting from Server
2017-07-05 17:37:48,863 - DEBUG - Connecting to Server
2017-07-05 17:37:49,876 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:37:50,903 - DEBUG - Requesting historical data
2017-07-05 17:37:50,930 - DEBUG - Returned from Reply Handler
2017-07-05 17:37:51,947 - DEBUG - Disconnecting from Server
2017-07-05 17:37:51,986 - DEBUG - Connecting to Server
2017-07-05 17:37:52,998 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:37:54,025 - DEBUG - Requesting historical data
2017-07-05 17:37:54,051 - DEBUG - Returned from Reply Handler
2017-07-05 17:38:31,094 - DEBUG - Starting ESDailyOHLC
2017-07-05 17:38:31,110 - DEBUG - Connecting to Server
2017-07-05 17:38:32,113 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:38:33,116 - DEBUG - Requesting historical data
2017-07-05 17:38:33,130 - DEBUG - Returned from Reply Handler
2017-07-05 17:38:33,208 - DEBUG - test5 -1
2017-07-05 17:38:33,211 - DEBUG - In Reply Handler
2017-07-05 17:38:33,215 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:38:33,382 - DEBUG - Connected to Database
2017-07-05 17:38:33,461 - DEBUG - Ran Insert Script
2017-07-05 17:38:33,464 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:38:33,469 - DEBUG - Today is still  2017-07-05
2017-07-05 17:38:33,474 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:38:33,478 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:38:33,482 - DEBUG - Query is SELECT ID from ES where Date = "07/04/2017"
2017-07-05 17:38:33,509 - DEBUG - BB ID1 is (58,)
2017-07-05 17:38:33,514 - DEBUG - Query is SELECT ID from ES where Date = "06/22/2017"
2017-07-05 17:38:33,541 - DEBUG - BB ID1 is (58,)
2017-07-05 17:38:33,543 - DEBUG - BB ID2 is (51,)
2017-07-05 17:38:33,546 - DEBUG - Query is SELECT round(Avg(Close),5) as Avg from ES where ID BETWEEN 51 AND 58;
2017-07-05 17:38:33,573 - DEBUG - BBMovAvg is (2427.95312,)
2017-07-05 17:38:33,575 - DEBUG - Query is UPDATE hasPosition SET BB_STRATMovingAvgValue = 2427.95312 where CCY ='ES';
2017-07-05 17:38:33,638 - DEBUG - Flag set to 1
2017-07-05 17:38:33,642 - DEBUG - test5 -1
2017-07-05 17:38:33,648 - DEBUG - In Reply Handler
2017-07-05 17:38:34,135 - DEBUG - Disconnecting from Server
2017-07-05 17:38:34,145 - DEBUG - Finished ES Daily OHLC
2017-07-05 17:40:32,326 - DEBUG - Starting GEDailyOHLC
2017-07-05 17:40:32,357 - DEBUG - Connecting to Server
2017-07-05 17:40:33,368 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:40:34,376 - DEBUG - Requesting historical data
2017-07-05 17:40:34,388 - DEBUG - Returned from Reply Handler
2017-07-05 17:40:35,402 - DEBUG - Disconnecting from Server
2017-07-05 17:40:35,460 - DEBUG - Connecting to Server
2017-07-05 17:40:36,468 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:40:37,477 - DEBUG - Requesting historical data
2017-07-05 17:40:37,495 - DEBUG - Returned from Reply Handler
2017-07-05 17:40:38,509 - DEBUG - Disconnecting from Server
2017-07-05 17:40:38,535 - DEBUG - Connecting to Server
2017-07-05 17:40:39,545 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:40:40,553 - DEBUG - Requesting historical data
2017-07-05 17:40:40,570 - DEBUG - Returned from Reply Handler
2017-07-05 17:40:41,582 - DEBUG - Disconnecting from Server
2017-07-05 17:40:41,644 - DEBUG - Connecting to Server
2017-07-05 17:40:42,650 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:40:43,658 - DEBUG - Requesting historical data
2017-07-05 17:40:43,670 - DEBUG - Returned from Reply Handler
2017-07-05 17:40:44,684 - DEBUG - Disconnecting from Server
2017-07-05 17:40:44,716 - DEBUG - Connecting to Server
2017-07-05 17:40:45,727 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:40:46,735 - DEBUG - Requesting historical data
2017-07-05 17:40:46,748 - DEBUG - Returned from Reply Handler
2017-07-05 17:40:47,761 - DEBUG - Disconnecting from Server
2017-07-05 17:40:47,804 - DEBUG - Connecting to Server
2017-07-05 17:41:55,552 - DEBUG - Starting GEDailyOHLC
2017-07-05 17:41:55,576 - DEBUG - Connecting to Server
2017-07-05 17:41:56,579 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:41:57,581 - DEBUG - Requesting historical data
2017-07-05 17:41:57,590 - DEBUG - Returned from Reply Handler
2017-07-05 17:41:58,599 - DEBUG - Disconnecting from Server
2017-07-05 17:41:58,638 - DEBUG - Connecting to Server
2017-07-05 17:41:59,642 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:00,643 - DEBUG - Requesting historical data
2017-07-05 17:42:00,657 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:01,662 - DEBUG - Disconnecting from Server
2017-07-05 17:42:01,690 - DEBUG - Connecting to Server
2017-07-05 17:42:02,694 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:03,698 - DEBUG - Requesting historical data
2017-07-05 17:42:03,706 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:04,711 - DEBUG - Disconnecting from Server
2017-07-05 17:42:04,748 - DEBUG - Connecting to Server
2017-07-05 17:42:05,758 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:06,762 - DEBUG - Requesting historical data
2017-07-05 17:42:06,773 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:07,790 - DEBUG - Disconnecting from Server
2017-07-05 17:42:07,825 - DEBUG - Connecting to Server
2017-07-05 17:42:08,853 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:09,857 - DEBUG - Requesting historical data
2017-07-05 17:42:09,881 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:10,887 - DEBUG - Disconnecting from Server
2017-07-05 17:42:10,947 - DEBUG - Connecting to Server
2017-07-05 17:42:11,951 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:12,954 - DEBUG - Requesting historical data
2017-07-05 17:42:12,976 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:13,981 - DEBUG - Disconnecting from Server
2017-07-05 17:42:14,015 - DEBUG - Connecting to Server
2017-07-05 17:42:15,019 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:16,022 - DEBUG - Requesting historical data
2017-07-05 17:42:16,034 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:17,045 - DEBUG - Disconnecting from Server
2017-07-05 17:42:17,080 - DEBUG - Connecting to Server
2017-07-05 17:42:18,083 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:19,086 - DEBUG - Requesting historical data
2017-07-05 17:42:19,099 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:20,105 - DEBUG - Disconnecting from Server
2017-07-05 17:42:20,180 - DEBUG - Connecting to Server
2017-07-05 17:42:21,199 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:22,201 - DEBUG - Requesting historical data
2017-07-05 17:42:22,234 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:23,239 - DEBUG - Disconnecting from Server
2017-07-05 17:42:23,276 - DEBUG - Connecting to Server
2017-07-05 17:42:24,282 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:25,285 - DEBUG - Requesting historical data
2017-07-05 17:42:25,294 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:26,310 - DEBUG - Disconnecting from Server
2017-07-05 17:42:26,397 - DEBUG - Connecting to Server
2017-07-05 17:42:27,407 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:28,410 - DEBUG - Requesting historical data
2017-07-05 17:42:28,420 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:29,431 - DEBUG - Disconnecting from Server
2017-07-05 17:42:29,469 - DEBUG - Connecting to Server
2017-07-05 17:42:30,476 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:31,479 - DEBUG - Requesting historical data
2017-07-05 17:42:31,488 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:32,501 - DEBUG - Disconnecting from Server
2017-07-05 17:42:32,544 - DEBUG - Connecting to Server
2017-07-05 17:42:33,548 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:34,549 - DEBUG - Requesting historical data
2017-07-05 17:42:34,562 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:35,578 - DEBUG - Disconnecting from Server
2017-07-05 17:42:35,606 - DEBUG - Connecting to Server
2017-07-05 17:42:36,615 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:37,617 - DEBUG - Requesting historical data
2017-07-05 17:42:37,625 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:38,643 - DEBUG - Disconnecting from Server
2017-07-05 17:42:38,677 - DEBUG - Connecting to Server
2017-07-05 17:42:39,688 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:40,691 - DEBUG - Requesting historical data
2017-07-05 17:42:40,700 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:41,716 - DEBUG - Disconnecting from Server
2017-07-05 17:42:41,749 - DEBUG - Connecting to Server
2017-07-05 17:42:42,751 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:42:43,754 - DEBUG - Requesting historical data
2017-07-05 17:42:43,761 - DEBUG - Returned from Reply Handler
2017-07-05 17:42:44,778 - DEBUG - Disconnecting from Server
2017-07-05 17:42:44,809 - DEBUG - Connecting to Server
2017-07-05 17:43:32,711 - DEBUG - Starting GEDailyOHLC
2017-07-05 17:43:32,735 - DEBUG - Connecting to Server
2017-07-05 17:43:33,739 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:43:34,747 - DEBUG - Requesting historical data
2017-07-05 17:43:34,754 - DEBUG - Returned from Reply Handler
2017-07-05 17:43:35,766 - DEBUG - Disconnecting from Server
2017-07-05 17:43:35,787 - DEBUG - Connecting to Server
2017-07-05 17:43:36,796 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:43:37,803 - DEBUG - Requesting historical data
2017-07-05 17:43:37,811 - DEBUG - Returned from Reply Handler
2017-07-05 17:43:38,821 - DEBUG - Disconnecting from Server
2017-07-05 17:43:38,848 - DEBUG - Connecting to Server
2017-07-05 17:43:39,855 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:11,518 - DEBUG - Starting GEDailyOHLC
2017-07-05 17:44:11,532 - DEBUG - Connecting to Server
2017-07-05 17:44:12,535 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:13,537 - DEBUG - Requesting historical data
2017-07-05 17:44:13,551 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:14,553 - DEBUG - Disconnecting from Server
2017-07-05 17:44:14,574 - DEBUG - Connecting to Server
2017-07-05 17:44:15,579 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:16,580 - DEBUG - Requesting historical data
2017-07-05 17:44:16,590 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:17,597 - DEBUG - Disconnecting from Server
2017-07-05 17:44:17,623 - DEBUG - Connecting to Server
2017-07-05 17:44:18,630 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:19,633 - DEBUG - Requesting historical data
2017-07-05 17:44:19,648 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:20,652 - DEBUG - Disconnecting from Server
2017-07-05 17:44:20,671 - DEBUG - Connecting to Server
2017-07-05 17:44:21,675 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:22,678 - DEBUG - Requesting historical data
2017-07-05 17:44:22,687 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:23,691 - DEBUG - Disconnecting from Server
2017-07-05 17:44:23,718 - DEBUG - Connecting to Server
2017-07-05 17:44:24,723 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:25,726 - DEBUG - Requesting historical data
2017-07-05 17:44:25,736 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:26,742 - DEBUG - Disconnecting from Server
2017-07-05 17:44:26,773 - DEBUG - Connecting to Server
2017-07-05 17:44:27,779 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:28,782 - DEBUG - Requesting historical data
2017-07-05 17:44:28,792 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:29,802 - DEBUG - Disconnecting from Server
2017-07-05 17:44:29,836 - DEBUG - Connecting to Server
2017-07-05 17:44:30,842 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:31,845 - DEBUG - Requesting historical data
2017-07-05 17:44:31,854 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:32,869 - DEBUG - Disconnecting from Server
2017-07-05 17:44:32,900 - DEBUG - Connecting to Server
2017-07-05 17:44:33,906 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:34,910 - DEBUG - Requesting historical data
2017-07-05 17:44:34,920 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:35,932 - DEBUG - Disconnecting from Server
2017-07-05 17:44:35,991 - DEBUG - Connecting to Server
2017-07-05 17:44:36,998 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:44:38,000 - DEBUG - Requesting historical data
2017-07-05 17:44:38,009 - DEBUG - Returned from Reply Handler
2017-07-05 17:44:39,027 - DEBUG - Disconnecting from Server
2017-07-05 17:44:39,062 - DEBUG - Connecting to Server
2017-07-05 17:44:40,069 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:45:57,283 - DEBUG - Starting GEDailyOHLC
2017-07-05 17:45:57,299 - DEBUG - Connecting to Server
2017-07-05 17:45:58,303 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:45:59,306 - DEBUG - Requesting historical data
2017-07-05 17:45:59,312 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:00,148 - DEBUG - test5 -1
2017-07-05 17:46:00,151 - DEBUG - In Reply Handler
2017-07-05 17:46:00,155 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:00,322 - DEBUG - Disconnecting from Server
2017-07-05 17:46:00,468 - DEBUG - Connecting to Server
2017-07-05 17:46:00,577 - DEBUG - Connected to Database
2017-07-05 17:46:00,657 - DEBUG - Ran Insert Script
2017-07-05 17:46:00,659 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:00,661 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:00,663 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:00,666 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:00,668 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:00,698 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:00,723 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:00,726 - DEBUG - test5 -1
2017-07-05 17:46:00,729 - DEBUG - In Reply Handler
2017-07-05 17:46:01,474 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:02,476 - DEBUG - Requesting historical data
2017-07-05 17:46:02,489 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:02,594 - DEBUG - test5 -1
2017-07-05 17:46:02,598 - DEBUG - In Reply Handler
2017-07-05 17:46:02,601 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:02,742 - DEBUG - Connected to Database
2017-07-05 17:46:02,836 - DEBUG - Ran Insert Script
2017-07-05 17:46:02,839 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:02,845 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:02,849 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:02,853 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:02,858 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:02,887 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:02,916 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:02,921 - DEBUG - test5 -1
2017-07-05 17:46:02,926 - DEBUG - In Reply Handler
2017-07-05 17:46:03,493 - DEBUG - Disconnecting from Server
2017-07-05 17:46:03,518 - DEBUG - Connecting to Server
2017-07-05 17:46:04,528 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:05,531 - DEBUG - Requesting historical data
2017-07-05 17:46:05,544 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:05,635 - DEBUG - test5 -1
2017-07-05 17:46:05,640 - DEBUG - In Reply Handler
2017-07-05 17:46:05,645 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:06,077 - DEBUG - Connected to Database
2017-07-05 17:46:06,164 - DEBUG - Ran Insert Script
2017-07-05 17:46:06,167 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:06,173 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:06,177 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:06,181 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:06,185 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:06,214 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:06,240 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:06,244 - DEBUG - test5 -1
2017-07-05 17:46:06,250 - DEBUG - In Reply Handler
2017-07-05 17:46:06,549 - DEBUG - Disconnecting from Server
2017-07-05 17:46:06,590 - DEBUG - Connecting to Server
2017-07-05 17:46:07,592 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:08,595 - DEBUG - Requesting historical data
2017-07-05 17:46:08,611 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:08,690 - DEBUG - test5 -1
2017-07-05 17:46:08,693 - DEBUG - In Reply Handler
2017-07-05 17:46:08,697 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:08,858 - DEBUG - Connected to Database
2017-07-05 17:46:08,939 - DEBUG - Ran Insert Script
2017-07-05 17:46:08,943 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:08,949 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:08,954 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:08,961 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:08,966 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:08,997 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:09,032 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:09,037 - DEBUG - test5 -1
2017-07-05 17:46:09,044 - DEBUG - In Reply Handler
2017-07-05 17:46:09,619 - DEBUG - Disconnecting from Server
2017-07-05 17:46:09,648 - DEBUG - Connecting to Server
2017-07-05 17:46:10,654 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:11,659 - DEBUG - Requesting historical data
2017-07-05 17:46:11,671 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:11,757 - DEBUG - test5 -1
2017-07-05 17:46:11,762 - DEBUG - In Reply Handler
2017-07-05 17:46:11,766 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:12,180 - DEBUG - Connected to Database
2017-07-05 17:46:12,274 - DEBUG - Ran Insert Script
2017-07-05 17:46:12,278 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:12,284 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:12,289 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:12,293 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:12,298 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:12,325 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:12,351 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:12,356 - DEBUG - test5 -1
2017-07-05 17:46:12,361 - DEBUG - In Reply Handler
2017-07-05 17:46:12,680 - DEBUG - Disconnecting from Server
2017-07-05 17:46:12,711 - DEBUG - Connecting to Server
2017-07-05 17:46:13,713 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:14,716 - DEBUG - Requesting historical data
2017-07-05 17:46:14,729 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:14,813 - DEBUG - test5 -1
2017-07-05 17:46:14,815 - DEBUG - In Reply Handler
2017-07-05 17:46:14,818 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:14,940 - DEBUG - Connected to Database
2017-07-05 17:46:15,045 - DEBUG - Ran Insert Script
2017-07-05 17:46:15,048 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:15,054 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:15,058 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:15,063 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:15,067 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:15,104 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:15,129 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:15,134 - DEBUG - test5 -1
2017-07-05 17:46:15,140 - DEBUG - In Reply Handler
2017-07-05 17:46:15,737 - DEBUG - Disconnecting from Server
2017-07-05 17:46:15,771 - DEBUG - Connecting to Server
2017-07-05 17:46:16,778 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:17,781 - DEBUG - Requesting historical data
2017-07-05 17:46:17,793 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:17,894 - DEBUG - test5 -1
2017-07-05 17:46:17,896 - DEBUG - In Reply Handler
2017-07-05 17:46:17,899 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:18,310 - DEBUG - Connected to Database
2017-07-05 17:46:18,420 - DEBUG - Ran Insert Script
2017-07-05 17:46:18,422 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:18,425 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:18,429 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:18,432 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:18,434 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:18,460 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:18,482 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:18,485 - DEBUG - test5 -1
2017-07-05 17:46:18,487 - DEBUG - In Reply Handler
2017-07-05 17:46:18,801 - DEBUG - Disconnecting from Server
2017-07-05 17:46:18,838 - DEBUG - Connecting to Server
2017-07-05 17:46:19,841 - DEBUG - Registered HistoricalData Reply Handler
2017-07-05 17:46:20,844 - DEBUG - Requesting historical data
2017-07-05 17:46:20,856 - DEBUG - Returned from Reply Handler
2017-07-05 17:46:20,931 - DEBUG - test5 -1
2017-07-05 17:46:20,934 - DEBUG - In Reply Handler
2017-07-05 17:46:20,936 - DEBUG - Valid Price Found (OPEN NOT -1)
2017-07-05 17:46:21,056 - DEBUG - Connected to Database
2017-07-05 17:46:21,144 - DEBUG - Ran Insert Script
2017-07-05 17:46:21,149 - DEBUG - Yesterday2 was 07/04/2017
2017-07-05 17:46:21,154 - DEBUG - Today is still  2017-07-05
2017-07-05 17:46:21,158 - DEBUG - Date shifted back 10 is 2017-06-22
2017-07-05 17:46:21,163 - DEBUG - First Date of BB Moving Average is 06/22/2017
2017-07-05 17:46:21,167 - DEBUG - Query is SELECT ID from GE where Date = "07/04/2017"
2017-07-05 17:46:21,194 - DEBUG - Query is SELECT ID from GE where Date = "06/22/2017"
2017-07-05 17:46:21,218 - ERROR - Exception in message dispatch.  Handler 'reply_handler' for 'historicalData'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\python3.4\lib\site-packages\ib\opt\dispatcher.py", line 44, in __call__
    results.append(listener(message))
  File "C:/Users/Michael/Documents/GitHub/Autotasks/autotasks/PythonScripts/GEdailyOHLC.py", line 112, in reply_handler
    logger.debug('BB ID1 is %s', ID1)
UnboundLocalError: local variable 'ID1' referenced before assignment
2017-07-05 17:46:21,221 - DEBUG - test5 -1
2017-07-05 17:46:21,223 - DEBUG - In Reply Handler
2017-07-05 17:46:21,866 - DEBUG - Disconnecting from Server
2017-07-05 17:46:21,894 - DEBUG - Connecting to Server
2017-07-05 17:46:22,902 - DEBUG - Registered HistoricalData Reply Handler
2017-07-09 16:40:01,233 - DEBUG - Starting FDailyOHLC
2017-07-09 16:40:01,282 - DEBUG - Connecting to Server
2017-07-09 16:40:02,288 - DEBUG - Registered HistoricalData Reply Handler
2017-07-09 16:40:03,296 - DEBUG - Product is M6E
2017-07-09 16:40:03,303 - DEBUG - Requesting historical data
2017-07-09 16:40:03,322 - DEBUG - Returned from Reply Handler
2017-07-09 16:40:04,334 - DEBUG - Disconnecting from Server
2017-07-09 16:40:04,359 - DEBUG - Connecting to Server
2017-07-09 16:40:05,368 - DEBUG - Registered HistoricalData Reply Handler
2017-07-09 16:40:06,376 - DEBUG - Product is -1
